[package]
name = "compiler-vyper"
version = "1.3.2"
authors = [
    "Alex Zarudnyy <a.zarudnyy@matterlabs.dev>",
]
license = "MIT OR Apache-2.0"
edition = "2021"
description = "The zkEVM Vyper compiler"

[[bin]]
name = "zkvyper"
path = "src/zkvyper/main.rs"

[lib]
doctest = false

[dependencies]
structopt = { version = "0.3", default-features = false }
shell-words = "1.1"
colored = "2.0"
anyhow = "1.0"

rayon = "1.6"

serde = { version = "1.0", "features" = [ "derive" ] }
serde_json = { version = "1.0", features = [ "arbitrary_precision", "unbounded_depth" ]}
serde_stacker = "0.1"
lazy_static = "1.4"
hex = "0.4"
semver = { version = "1.0", features = [ "serde" ] }

zkevm_opcode_defs = { git = "https://github.com/matter-labs/era-zkevm_opcode_defs", branch = "main" }
zkevm-assembly = { git = "https://github.com/matter-labs/era-zkEVM-assembly", branch = "main" }

compiler-common = { git = "https://github.com/matter-labs/era-compiler-common", rev = "a6c5b02e4f149f82f1c3821a6f258363308abd2a" }
compiler-llvm-context = { git = "https://github.com/matter-labs/era-compiler-llvm-context", rev = "9ef35644d9801ed6d42bc38d9b639520a3ab3def" }

[dependencies.inkwell]
git = "https://github.com/matter-labs-forks/inkwell"
branch = "llvm-15"
default-features = false
features = ["llvm15-0", "no-libffi-linking", "target-syncvm"]

[target.'cfg(target_env = "musl")'.dependencies]
mimalloc = { version = "*", default-features = false }
